[toolchain]

[features]
seeds = true

[programs.localnet]
nexdraw = "DRAWDnBHxRrointnFhaLEsexAXjgW2rUqZU7qpGqxonP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"
